In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)
print(type(arr))

arr2d = np.array([[1, 2], [2, 7], [9, 10]])
print(arr2d)
print(arr2d.shape) # (3, 2) : 3 rows * 2 columns

# Normal Python
list_of_list = [[1, 2], [2, 7], [9, 10]]
print(list_of_list)

print(arr + 1) # [2 3 4]
print(arr ** 2) # [1 4 9]
print(arr * 2) # [2 4 6]

list1 = [1,2,3]
print(list1 * 2) # [1, 2, 3, 1, 2, 3]

[1 2 3]
<class 'numpy.ndarray'>
[[ 1  2]
 [ 2  7]
 [ 9 10]]
(3, 2)
[[1, 2], [2, 7], [9, 10]]
[2 3 4]
[1 4 9]
[2 4 6]
[1, 2, 3, 1, 2, 3]


In [15]:
arr3 = np.array([100, 8, 6, 80])
print(np.mean(arr3)) # 48.5
print(np.median(arr3)) # 44.0
print(np.min(arr3)) # 6
print(np.max(arr3)) # 100
print(np.std(arr3)) # 42.104

arr4_reshaped = arr3.reshape(2, 2)
print(arr4_reshaped)

print(arr3.size)

48.5
44.0
6
100
42.10403781111736
[[100   8]
 [  6  80]]
4
